--- 
- name: CONFIGURE STATIC IP
  hosts: CSR1kv 
  gather_facts: false 
  connection: local 

  tasks: 
   - name: SET IP IN LOOPBACK INT  
     ios_config:
      lines: 
       #parents: "configure terminal" 
    #ios_command:
      #command: 
         #- description IPv6 ADDRESS  
         #- ipv6 address 2001:db8:acad:1::1/64 
         #- ipv6 address fe80::1:1 link-local
      - ip static 172.16.0.0/16 192.168.10.1
 
  # - name: SHOW IPv6 INTERFACE BRIEF  
  #   ios_command: 
  #     commands: 
  #       - show ipv6 interface brief 
  #   register: output 
 
   - name: SAVE OUTPUT ./test/ 
     copy:  
       content: "{{ output.stdout[0] }}" 
       dest: "test/static_output_{{ inventory_hostname }}.txt" 
