---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG 
  hosts: CSR1kv 
  gather_facts: false 
  connection: local 

  tasks: 
   - name: DISPLAYING THE RUNNING-CONFIG 
     ios_command: 
       commands: 
         - show version
         #- show ip interface brief   
     register: config 

   - name: SAVE OUTPUT TO ./test/ 
     copy: 
       content: "{{ config.stdout[0] }}" 
       dest: "test/show_{{ inventory_hostname }}.txt" 
