---
- name: DISPLAY RUNNING-CONFIG 
  hosts: CSR1kv 
  gather_facts: false 
  connection: local 

  tasks: 
   - name: DISPLAYING ROUTING TABLE 
     ios_command: 
       commands: 
         #- show version
         - show ip interface brief   
     register: config 

   - name: SAVE OUTPUT TO ./test/ 
     copy: 
       content: "{{ config.stdout[0] }}" 
       dest: "test/show_routingtable_{{ inventory_hostname }}.txt" 
